source "https://rubygems.org"#tells your app where to get the gems from

gem "rake" #gives us tasks and dependencies that can be specified in standard Ruby syntax (don't worry about it if you don't get it)
# gem "standalone_migrations" #helps create migrations
# gem "activerecord" #the ORM
gem "sinatra-activerecord"
gem "pg" #allows us to use postgresql as a DBMS for our app
gem "pry"
